### ISSUE TITLE
Validation of the 202006 reference design run

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4_design_sim_tool#14]
Run described in #13,
see documentation at:
https://github.com/CMB-S4/s4mapbasedsims/tree/master/202006_reference_design

I am working on validating the atmosphere and noise.

* SAT full mission is fine
* LAT 9/13 pass, 4 fail

**Comment by zonca** [comment]
@keskitalo for example LFL2 at Pole, it seems to me the noise covariance matrix is 20% off.
Can you please crosscheck?

See my notebook here: https://gist.github.com/zonca/e88a1364c69d798d5802c03f7666c2a1

The LFL1 at Pole instead has noise covariance matrix within 5% and good agreement on spectra:

![image](https://user-images.githubusercontent.com/383090/86554555-d144ac80-bf02-11ea-964e-5374df350065.png)

Channels failing:

* `LAT-HFL1_pole`
* `LAT-HFL2_pole`
* `LAT-LFL2_pole`
* `LAT-MFL2_pole`

**Comment by zonca** [comment]
This is instead the one that fails:

![image](https://user-images.githubusercontent.com/383090/86702228-9c4e5d80-bfc7-11ea-86e6-b4ce6ef182bb.png)

**Comment by keskitalo** [comment]
@zonca I verified that the noise matrices accurately model the noise in the pure noise maps. Scaling the pixel values with the estimated noise covariance produces RMS=1. The problem seems to be in the atmospheric maps. I tried tricking the code to re-use the atmospheric realization from another LAT (to avoid the costly caching step) but it seems have confused the hardware selection so detectors are picked from more than one optics tube. The survey footprint of the atmospheric simulation does not perfectly match the the footprint of the other components. The mismatch is worst for Pole LAT LFL. We shall have to accept this as a feature of the simulation but will make sure not to recycle the atmospheric realization in the future.

**Comment by keskitalo** [comment]
@zonca You are probably using the Chile LAT noise levels for the Pole LAT test. This is part of the noise level update. In the hardware map the Pole LAT bands have an extra "P" in their name: `LFL1 -> LFPL1` etc. Here are the NET values and their ratios:

```
band  NET(Pole) NET(Chile)  Pole / Chile
LFPL1     445.0      429.0      1.037
LFPL2     320.0      261.0      1.226
MFPL1     347.0      305.0      1.138
MFPL2     374.0      385.0      0.971
HFPL1     664.0      792.0      0.838
HFPL2    1609.0     1990.0      0.809

```

**Comment by zonca** [comment]
I noticed those channels and I thought it was something related to the new 85 tubes focal plane but was not affecting our simulations. Thanks, I'll resume the validation. Hope this is the last issue I encounter.

**Comment by zonca** [comment]
@keskitalo you exchanged pole and chile in your table. Anyway I crosschecked with `s4sim` and now exported here: https://github.com/CMB-S4/s4mapbasedsims/blob/master/202006_foregrounds_extragalactic_cmb_tophat/cmbs4_tophat.csv

The `LAT-LFL2_pole` white noise covariance test now passes, I'm running all the others and preparing the release.

**Comment by zonca** [comment]
ok, all my validation tests pass,
the release seems fine to me.

I did a quick crosscheck also of the foregrounds, the transfer function between inputs and outputs looks complicated, so hard to assess, but at least the order of magnitude looks fine.

@cbischoff @keskitalo @jdborrill see the documentation here: https://github.com/CMB-S4/s4mapbasedsims/blob/master/202006_reference_design/README.md
